version: '3.1'
services:
  node-app:
    build: .
    ports:
      - 80:80
    depends_on:
      - postgres
    networks:
      - my-network
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: marvel_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5435:5435"
    networks:
      - my-network
    command: -p 5435
networks:
  my-network:
    driver: bridge
